### ISSUE TITLE
1.17 compatibility

### ISSUE THREAD

**Issue by herobrine99dan** [herobrine99dan/NESS-Reloaded#146]
**What server version are you running?**Spigot 1.17

**What version of NESS Reloaded are you running?**Latest Dev Build

**Describe the Bug** Mojang completely changed the position of the classes

**Do you have some videos / screenshots?** No

**If it is an error, do you have logs?** 

> [20:01:19] [Server thread/INFO]: [NESS] Enabling NESS v2.8.0-SNAPSHOT
> [20:01:19] [Server thread/INFO]: Floodgate was detected, NESS Reloaded will fix checks for Geyser's users!
> [20:01:19] [Server thread/ERROR]: Error occurred while enabling NESS v2.8.0-SNAPSHOT (Is it up to date?)
> com.github.ness.reflect.ReflectionException: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
> at com.github.ness.reflect.SimpleClassLocator.classForName(SimpleClassLocator.java:49) ~[?:?]
> at com.github.ness.reflect.SimpleClassLocator.getNmsClass(SimpleClassLocator.java:26) ~[?:?]
> at com.github.ness.packets.NetworkReflectionCreation.create(NetworkReflectionCreation.java:34) ~[?:?]
> at com.github.ness.NessAnticheat.<init>(NessAnticheat.java:81) ~[?:?]
> at com.github.ness.NessPlugin.onEnable(NessPlugin.java:32) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at java.lang.Thread.run(Unknown Source) [?:?]
> Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
> at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3124-Spigot-66f9d3c-384e116]
> at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
> at java.lang.Class.forName0(Native Method) ~[?:?]
> at java.lang.Class.forName(Unknown Source) ~[?:?]
> at com.github.ness.reflect.SimpleClassLocator.classForName(SimpleClassLocator.java:47) ~[?:?]
> ... 14 more

**Comment by herobrine99dan** [comment]
Done with https://github.com/herobrine99dan/NESS-Reloaded/pull/152
