### ISSUE TITLE
Console Error on 1.12.2

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#25]
[05:36:17 ERROR]: Could not pass event PlayerTeleportEvent to NESS v0.1.0-SNAPSHOT
org.bukkit.event.EventException: NESS made a mistake in listening to an event. Please report this error on Github.
        at com.github.ness.CheckManager$1.execute(CheckManager.java:82) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:795) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:764) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:755) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.stopRiding(EntityPlayer.java:760) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:451) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1167) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:361) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at com.github.ness.check.TeleportEvent.checkEvent(TeleportEvent.java:16) ~[?:?]
        at com.github.ness.check.TeleportEvent.checkEvent(TeleportEvent.java:1) ~[?:?]
        at com.github.ness.check.AbstractCheck.checkAnyEvent(AbstractCheck.java:60) ~[?:?]
        at com.github.ness.CheckManager$1.lambda$0(CheckManager.java:79) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_251]
        at com.github.ness.CheckManager$1.execute(CheckManager.java:79) ~[?:?]
        ... 16 more

**Comment by herobrine99dan** [comment]
Okay, i will fix this

**Comment by A248** [comment]
This error has already been solved in the master branch, NESS just needs to be recompiled.
