### ISSUE TITLE
crash bug on 1.12.2

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#45]
**What server version are you running?**
paper 1.12.2
**What version of NESS Reloaded are you running?**
1.9.9
**Describe the Bug**
if you flag the fly check novelocity or other fly checks it will start flagging vls a ton and crash the server i think its something to do with the dragback thing
**Do you have some videos / screenshots?**
no
**If it is an error, do you have logs?**
https://hastebin.com/vumokofoho.md

**Comment by herobrine99dan** [comment]
do you have enabled the kick?
This issue usually happens when the anticheat doesn't kick the player for too long

**Comment by Oecher1** [comment]
> do you have enabled the kick?
> This issue usually happens when the anticheat doesn't kick the player for too long

i have kicks off to test the anticheat

**Comment by herobrine99dan** [comment]
Then this is cause, i don't know how, but when you turn off kicks it starts to become crazy.
AnyWay i will not close this issue until we find a solution

**Comment by herobrine99dan** [comment]
Can you try if you get this crash error with this new build?
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5130334/NESS.zip)

**Comment by Oecher1** [comment]
> Can you try if you get this crash error with this new build?
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5130334/NESS.zip)

ok

**Comment by Oecher1** [comment]
> Can you try if you get this crash error with this new build?
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5130334/NESS.zip)

i cant even join my 1.8.8 server with this on now

[07:20:21 WARN]: [NESS] Task #23 for NESS v2.1.0-SNAPSHOT generated an exception
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.warn(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.warn(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
        at com.github.ness.CheckManager.getAllChecks(CheckManager.java:78) ~[?:?]
        ... 8 more
[07:20:21 INFO]: [Vault] Checking for Updates ...
[07:20:21 WARN]: [PermissionsEx] The updater could not find any files for the project id 31279
[07:20:21 INFO]: Spawning a test npc 'steve' to fetch npcs' skin. The npc will be removed in 10 seconds.
[07:20:21 INFO]: Preloaded 49 matches in 2 seconds.
[07:20:23 WARN]: [Vault] Stable Version: 1.7.3 is out! You are still running version: 1.7.2
[07:20:23 WARN]: [Vault] Update at: https://dev.bukkit.org/projects/vault
[07:20:25 INFO]: Player practice commands registered: night, day, practicecommands
[07:21:21 INFO]: UUID of player jrdenney is 833092ae-e444-3002-b118-dfe62c995a7b
[07:21:21 ERROR]: Could not pass event PlayerJoinEvent to NESS v2.1.0-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
        at com.github.ness.CheckManager.lambda$getPlayer$1(CheckManager.java:113) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:1.8.0_261]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[?:?]
        at com.github.ness.CheckManager.getPlayer(CheckManager.java:112) ~[?:?]
        at com.github.ness.CoreListener.onJoin(CoreListener.java:26) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 14 more
[07:21:21 INFO]: jrdenney[/127.0.0.1:57480] logged in with entity id 88 at ([world]265.3943683476812, 54.0, 1363.0313302973084)
[07:21:21 INFO]: Loaded jrdenney's data in 110 ms.
[07:21:21 INFO]: jrdenney lost connection: Internal Exception: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
[07:21:21 INFO]: jrdenney left the game.
[07:21:23 WARN]: handleDisconnection() called twice
[07:21:23 INFO]: UUID of player jrdenney is 833092ae-e444-3002-b118-dfe62c995a7b
[07:21:23 ERROR]: Could not pass event PlayerJoinEvent to NESS v2.1.0-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
        at com.github.ness.CheckManager.lambda$getPlayer$1(CheckManager.java:113) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:1.8.0_261]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
        at com.github.ness.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[?:?]
        at com.github.ness.CheckManager.getPlayer(CheckManager.java:112) ~[?:?]
        at com.github.ness.CoreListener.onJoin(CoreListener.java:26) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 14 more
[07:21:23 INFO]: jrdenney[/127.0.0.1:57489] logged in with entity id 89 at ([world]274.0, 54.0, 1403.0)
[07:21:23 INFO]: jrdenney lost connection: Internal Exception: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
[07:21:23 INFO]: jrdenney left the game.
[07:21:23 INFO]: Loaded jrdenney's data in 89 ms.
[07:21:25 WARN]: handleDisconnection() called twice

**Comment by herobrine99dan** [comment]
What Minecraft version are you using?

**Comment by A248** [comment]
@Oecher1 What kind of server are you running where Log4j doesn't exist? I opened up the Spigot 1.8.8 jar just now, and log4j2 is definitely present.

Did you reload the plugin or otherwise mess with classloading?

**Comment by A248** [comment]
b84c480acef785d8354d515dab54bc9baf6a8816 may have fixed it

**Comment by herobrine99dan** [comment]
I Will do another build and i Will give It to you here

**Comment by herobrine99dan** [comment]
Do you get this error with 2.2 version?

**Comment by herobrine99dan** [comment]
So do you get this error?
Does the new DragDown method crash the server?

**Comment by Oecher1** [comment]
> So do you get this error?
> Does the new DragDown method crash the server?

not really anymore

**Comment by herobrine99dan** [comment]
Okay i have fixed, i'm closing this issue.
