### ISSUE TITLE
Player moving spams console with errors

### ISSUE THREAD

**Issue by Robert9157** [herobrine99dan/NESS-Reloaded#51]
**What server version are you running?** 
1.15.1. Using ViaVersion plugin to extend support to 1.12-1.16.1. When noticing the error, I was logged in with 1.15.2

**What version of NESS Reloaded are you running?**
Version 0.1.0-SNAPSHOT

**Describe the Bug**
Making any sort of movement spams the console with an error, which is listed below.

**Do you have some videos / screenshots?**
![kép](https://user-images.githubusercontent.com/69000275/90321380-60ed6a00-df49-11ea-9f99-9bc7eab39808.png)

**If it is an error, do you have logs?**
[22:45:23] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to NESS v0.1.0-SNAPSHOT
org.bukkit.event.EventException: NESS made a mistake in listening to an event. Please report this error on Github.
at com.github.ness.CheckManager$1.execute(CheckManager.java:111) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:998) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:893) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoSuchFieldError: WEB
at com.github.ness.check.Fly.Check4(Fly.java:136) ~[?:?]
at com.github.ness.check.Fly.checkEvent(Fly.java:33) ~[?:?]
at com.github.ness.check.Fly.checkEvent(Fly.java:1) ~[?:?]
at com.github.ness.check.AbstractCheck.checkAnyEvent(AbstractCheck.java:60) ~[?:?]
at com.github.ness.CheckManager$1.lambda$0(CheckManager.java:108) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_265]
at com.github.ness.CheckManager$1.execute(CheckManager.java:108) ~[?:?]
... 17 more

**Comment by herobrine99dan** [comment]
Okay so this error doesn't exist on 1.12.2, so It Is an error with the Materiale Enum.
I Will make a fix later

**Comment by Robert9157** [comment]
Okay thank you. Please let me know when it is fixed

**Comment by herobrine99dan** [comment]
Here there is a developer build which should fix these errors.
If you can, try it and say to me if you get these errors.
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5084987/NESS.zip)

**Comment by herobrine99dan** [comment]
Can you try that build?

**Comment by Robert9157** [comment]
I can't, our hosting provider does not allow direct plugin uploading.

**Comment by Dqgs** [comment]
What server hosting company do you use because i recommend switching i can suggest you one if herobrine99dan doesn't mind

**Comment by herobrine99dan** [comment]
Okay you are using Aternos, After i have to test a lot of things, i Will test also this and i Will release an update.

**Comment by Robert9157** [comment]
Okay thank you. And yeah, I'm using Aternos. How did you know that?

**Comment by herobrine99dan** [comment]
Because another user use this Host and he needs a real update from spigot Page

**Comment by Robert9157** [comment]
Oh okay. Actually, about the dev build, I can try downloading it to my private 1.15.2 server on my PC for testing, it it could help.

**Comment by herobrine99dan** [comment]
There are some errors i have to fix

**Comment by herobrine99dan** [comment]
> Oh okay. Actually, about the dev build, I can try downloading it to my private 1.15.2 server on my PC for testing, it it could help.

[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5103765/NESS.zip)
If you can try this build in your computer to check if there are errors
